name: Tests
on:
  push:
    branches: [main, next]
  pull_request:
    branches: [main, next]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build libs
        run: npm run build
      - name: Install playwright browsers
        run: npx playwright install --with-deps
      - name: Tests
        run: npm run test
